### Window rules
#
    # Cachy TUI popups (wifi, audio, bluetooth): floating, no title bar
    for_window [app_id="org.cachy.impala"]  floating enable, border pixel 1
    for_window [app_id="org.cachy.wiremix"] floating enable, border pixel 1
    for_window [app_id="org.cachy.bluetui"] floating enable, border pixel 1
    for_window [app_id="satty"] floating enable, border pixel 1
    
    for_window [app_id="helium"] border pixel 1, opacity 1
    for_window [app_id="code-oss"] border pixel 1
